name = "DifferentialEquations"
uuid = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "6.16.0"

[deps]
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
DelayDiffEq = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiffEqFinancial = "5a0ffddc-d203-54b0-88ba-2c03c0fc2e67"
DiffEqJump = "c894b116-72e5-5b58-be3c-e6d8d4ac2b12"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
DiffEqPhysics = "055956cb-9e8b-5191-98cc-73ae4a59e68a"
DimensionalPlotRecipes = "c619ae07-58cd-5f6d-b883-8f17bd6a98f9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultiScaleArrays = "f9640e96-87f6-5992-9c3b-0743c6a49ffa"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
BoundaryValueDiffEq = "2.3"
DelayDiffEq = "5.18.0"
DiffEqBase = "6.12.2"
DiffEqCallbacks = "2.10"
DiffEqFinancial = "2.2"
DiffEqJump = "6.2.1"
DiffEqNoiseProcess = "3.6, 4.0, 5.0"
DiffEqPhysics = "3.2"
DimensionalPlotRecipes = "1"
MultiScaleArrays = "1.5"
OrdinaryDiffEq = "5.23.0"
ParameterizedFunctions = "5"
RecursiveArrayTools = "2"
Reexport = "0.2, 1.0"
SteadyStateDiffEq = "1.5"
StochasticDiffEq = "6.13.0"
Sundials = "3.8.1, 4.0"
julia = "1.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "SafeTestsets"]
